- name: "[1/3] Cài đặt chung cho tất cả các node"
  hosts: k8s_cluster
  roles:
    - common

- name: "[2/3] Khoi tao control plane"
  hosts: control_plane
  roles:
    - control_plane

- name: "[3/3] Join worker vao cluster"
  hosts: workers
  roles:
    - worker

- name: "[4/4] Triển khai Ingress Controller & Management Stack"
  hosts: control_plane
  vars:
    domain_suffix: "54.169.245.170.nip.io" # Thay bằng IP/Domain thực tế của ông
    rancher_password: "AdminSecurePass123"
  roles:
    - management_apps
