apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-cicd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io'
    chart: jenkins
    targetRevision: 5.x.x
    helm:
      values: |
        controller:
          componentName: "jenkins-controller"
          admin:
            username: "admin"
            password: "123abc@A"
          persistence:
            enabled: true
            size: "20Gi"
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod
            hostName: "jenkins.ops-study.xyz"
            tls:
              - secretName: jenkins-tls
                hosts:
                  - "jenkins.ops-study.xyz"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true